apiVersion: v1
kind: Service
metadata:
  name: nodeport-simple-service
spec:
  type: NodePort
  selector:
    app: kubernetes-simple-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080