apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: websample-ing
spec:
  rules:
  - host: localhost 
    http:
      paths:
      - backend:
          serviceName: websample
          servicePort: 5000
        path: /